### ISSUE TITLE
Takenmodule in project empty-tekst geven. (geen state) (...)

### ISSUE THREAD

**Issue by Duncank** [Duncank/5X#140]
Dat gaat dan om de "alles"-tab, waar die twee invoervakken in zitten.
En als je me zegt waar dat regeltje zit dan style ik m verder

**Comment by timramakers** [comment]
in models/loadActiviteit.php op r132! Ik weet niet wat je er precies van zou willen maken, iets als 'Voeg hieronder taken toe' of iets?
